#ifndef ARMV8_SYSCALL_H
#define ARMV8_SYSCALL_H

#define ARMV8_SYSCALL_SYNDROME_TEST 0
#define ARMV8_SYSCALL_SIMBENCH 1

#define ARMV8_EC_UNKNOWN 0x0
#define ARMV8_EC_SYSCALL 0x15

#define SYSCALL_IRQ_ENABLE 1
#define SYSCALL_IRQ_DISABLE 2
#define SYSCALL_MEM_INIT 3
#define SYSCALL_MMU_ENABLE 4
#define SYSCALL_MMU_DISABLE 5
#define SYSCALL_FLUSH_DCACHE 6
#define SYSCALL_FLUSH_ICACHE 7

void armv8_syscall(int call_no);

#endif
